knp_paginator:
    page_range: 5    # Nombre de pages visibles dans la pagination
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'  # Utilisation du style Bootstrap 5
